### ISSUE TITLE
use non generative api

### ISSUE THREAD

**Issue by c-cube** [Gbury/mSAT#12]
replace generative functors by mere functors (or modules), and provide a `type t` which wraps the state.

pros:
- state is more explicit
- globals are now embedded in `t` and can be gc'd
- more customizable: `val create: ?size:int -> ?callback:… -> unit -> t`
- easier to copy/(de)serialize if need be
- easier to integrate in other `type t`-based APIs
- more convenient (no local module necessary)

cons:
- change API

**Comment by Gbury** [comment]
I don't think that breaking the API is a big problem, as I don't get the felling there are a lot of mSAT users yet.

**Comment by timothee-haudebourg** [comment]
I can't use this in my project (yet) because of the generative api. Do you have any idea when the `type t` will be implemented?

**Comment by Gbury** [comment]
There is a pull request ( #11 ) implementing this suggestion. What slows me from merging it is that I'm currently writing my thesis with my main project using mSAT, so I'm not too keen on adapting it right now.

However, it could be possible for me to release the current version of mSAT, and then merge PR #11 . Though you'd have to pin the github repo to get the version with explicit state (at least until the merged version has been tested enough for a release). Would that help you ?

**Comment by timothee-haudebourg** [comment]
Yes that would help, thanks. But I didn't realized that it was included in https://github.com/Gbury/mSAT/pull/11, if you need some time I can just get it from this branch.
