### ISSUE TITLE
ability to push decisions from the theory

### ISSUE THREAD

**Issue by c-cube** [Gbury/mSAT#19]
would be useful for the theory to be able to make boolean decisions, for z3-style theory combination

**Comment by Gbury** [comment]
Would it be enough if before making a decision, the SAT asked the theory if it wanted to make a decision ?

**Comment by c-cube** [comment]
I'll have to think more about that :-)
It could be that the theory suggests a list of next decisions to make, a bit like assumptions, but the list would be dropped on backtracking?
